### ISSUE TITLE
I can't run this code 

### ISSUE THREAD

**Issue by vothaianh1997** [Js2Hou/Swin-CBIR#1]
Traceback (most recent call last):
  File "generate_DB.py", line 134, in <module>
    main()
  File "generate_DB.py", line 125, in main
    model = get_pretrained_model(config)
  File "/content/drive/MyDrive/ColabNotebooks/Swin-CBIR-main/utils.py", line 32, in get_pretrained_model
    checkpoint = torch.load(config.MODEL.RESUME, map_location='cpu')
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/swin_tiny_patch4_window7_224.pth'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1557) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
generate_DB.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-01-16_23:32:26
  host      : 0da41351b232
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1557)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by Js2Hou** [comment]
sorry, i didn't upload swin-transformer's checkpoint here, you can download it at [swin_tiny_patch4_window7_224.pth](https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth), and then move it into `checkpoints` path.

**Comment by vothaianh1997** [comment]
please.. Can you up full step how to run this code. Error in file  index.txt when i upload new dataset. i'm student and i need this source.And.. Happy new Year =)

**Comment by vothaianh1997** [comment]
can you give me your data .my error now .RuntimeError: Given groups=1, weight of size [96, 3, 4, 4], expected input[1, 4, 224, 224] to have 3 channels, but got 4 channels instead

**Comment by Js2Hou** [comment]
you can download my shared data here [https://www.aliyundrive.com/s/L7PSuEpJ3Df](https://www.aliyundrive.com/s/L7PSuEpJ3Df)

**Comment by vothaianh1997** [comment]
can you updata in github. I can't download .aliyundrive

**Comment by Js2Hou** [comment]
Yes, i have done so
